Repository litmuschaos/chaos-charts, pull requests merged in 2020-01, with the labels that each got.

#91 (Enhancement): Added/Removed permissions for cpu-hog experiment
  charts/generic/cpu-hog/experiment.yaml
Labels: enhancement

#87 (Enhancement): Added/Removed permissions for container kill experiment
  charts/generic/container-kill/experiment.yaml
Labels: enhancement

#92 Added scope field in pod-delete experiment
  charts/generic/pod-delete/experiment.yaml
Labels: bug

#88 (Enhancement): Added/Removed permissions for pod-network-latency experiment
  charts/generic/pod-network-latency/experiment.yaml
Labels: enhancement

#96 (fix): changing secret name to cloud secret
  charts/generic/disk-loss/experiment.yaml
Labels: bug

#94 (Enhancement): Added/Removed permissions for DISK-FILL experiment
  charts/generic/disk-fill/experiment.yaml
Labels: enhancement

#97 (Enhancement): Remove unnecessary permissions and resources for DISK-LOSS experiment
  charts/generic/disk-loss/experiment.yaml
Labels: enhancement

#98 Removed status from Permissions
  charts/generic/cpu-hog/experiment.yaml
Labels: bug

#101 (Enhancement):Added/Removed permissions for node-drain experiment
  charts/generic/drain-node/experiment.yaml
Labels: enhancement

#103 Added Docs link in charts of experiments
  charts/coredns/coredns-pod-delete/coredns-pod-delete.chartserviceversion.yaml
  charts/generic/drain-node/drain-node.chartserviceversion.yaml
Labels: documentation

#104 Added and removed platforms for experiments
  charts/generic/container-kill/container-kill.chartserviceversion.yaml
  charts/generic/disk-loss/disk-loss.chartserviceversion.yaml
  charts/generic/disk-loss/experiment.yaml
  charts/generic/drain-node/drain-node.chartserviceversion.yaml
  charts/generic/pod-cpu-hog/pod-cpu-hog.chartserviceversion.yaml
  charts/generic/pod-delete/pod-delete.chartserviceversion.yaml
  charts/generic/pod-network-corruption/pod-network-corruption.chartserviceversion.yaml
  charts/generic/pod-network-latency/pod-network-latency.chartserviceversion.yaml
  charts/generic/pod-network-loss/pod-network-loss.chartserviceversion.yaml
Labels: enhancement

#110 Added experiement link for coreDNS and Kafka experiment
  charts/coredns/coredns-pod-delete/coredns-pod-delete.chartserviceversion.yaml
  charts/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure.chartserviceversion.yaml
  charts/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure.chartserviceversion.yaml
Labels: enhancement

#109 Added experiment source code link inside chart for openEBS
  charts/openebs/openebs-pool-container-failure/openebs-pool-container-failure.chartserviceversion.yaml
  charts/openebs/openebs-pool-pod-failure/openebs-pool-pod-failure.chartserviceversion.yaml
  charts/openebs/openebs-target-container-failure/openebs-target-container-failure.chartserviceversion.yaml
  charts/openebs/openebs-target-network-delay/openebs-target-network-delay.chartserviceversion.yaml
  charts/openebs/openebs-target-network-loss/openebs-target-network-loss.chartserviceversion.yaml
  charts/openebs/openebs-target-pod-failure/openebs-target-pod-failure.chartserviceversion.yaml
Labels: enhancement

#108 Added experiment source code link inside charts
  charts/generic/container-kill/container-kill.chartserviceversion.yaml
  charts/generic/cpu-hog/cpu-hog.chartserviceversion.yaml
  charts/generic/disk-fill/disk-fill.chartserviceversion.yaml
  charts/generic/disk-loss/disk-loss.chartserviceversion.yaml
  charts/generic/node-drain/node-drain.chartserviceversion.yaml
  charts/generic/pod-cpu-hog/pod-cpu-hog.chartserviceversion.yaml
  charts/generic/pod-delete/pod-delete.chartserviceversion.yaml
  charts/generic/pod-network-corruption/pod-network-corruption.chartserviceversion.yaml
  charts/generic/pod-network-latency/pod-network-latency.chartserviceversion.yaml
  charts/generic/pod-network-loss/pod-network-loss.chartserviceversion.yaml
Labels: enhancement

#113 Added update verb in charts
  charts/coredns/coredns-pod-delete/experiment.yaml
  charts/generic/container-kill/experiment.yaml
  charts/generic/cpu-hog/experiment.yaml
  charts/generic/disk-fill/experiment.yaml
  charts/generic/disk-loss/experiment.yaml
  charts/generic/node-drain/experiment.yaml
  charts/generic/pod-cpu-hog/experiment.yaml
  charts/generic/pod-delete/experiment.yaml
  charts/generic/pod-network-corruption/experiment.yaml
  charts/generic/pod-network-latency/experiment.yaml
  charts/generic/pod-network-loss/experiment.yaml
Labels: lgtm

#119 (refactor): Add definition field in openebs-target-pool-failure
  charts/openebs/openebs-pool-container-failure/experiment.yaml
Labels: bug
