Repository litmuschaos/chaos-charts, pull requests merged in 2022-06, with the labels that each got.

#548 Updates GCP experiment charts
  charts/gcp/gcp-vm-disk-loss-by-label/experiment.yaml
  charts/gcp/gcp-vm-disk-loss-by-label/gcp-vm-disk-loss-by-label.chartserviceversion.yaml
  charts/gcp/gcp-vm-disk-loss/experiment.yaml
  charts/gcp/gcp-vm-disk-loss/gcp-vm-disk-loss.chartserviceversion.yaml
  charts/gcp/gcp-vm-instance-stop-by-label/engine.yaml
  charts/gcp/gcp-vm-instance-stop-by-label/experiment.yaml
  charts/gcp/gcp-vm-instance-stop-by-label/gcp-vm-instance-stop-by-label.chartserviceversion.yaml
  charts/gcp/gcp-vm-instance-stop/experiment.yaml
  charts/gcp/gcp-vm-instance-stop/gcp-vm-instance-stop.chartserviceversion.yaml
Labels: bug-fix

#549 Chore[New Exp]: Charts for HTTP Chaos Latency
  charts/generic/generic.chartserviceversion.yaml
  charts/generic/generic.package.yaml
  charts/generic/icons/pod-http-latency.png
  charts/generic/pod-http-latency/engine.yaml
  charts/generic/pod-http-latency/experiment.yaml
  charts/generic/pod-http-latency/pod-network-latency.chartserviceversion.yaml
  charts/generic/pod-http-latency/rbac-psp.yaml
  charts/generic/pod-http-latency/rbac.yaml
Labels: enhancement, READY FOR REVIEW

#553 Chore[Fix]: Http chaos latency not coming in chaos hub
  charts/generic/generic.package.yaml
  charts/generic/pod-http-latency/pod-http-latency.chartserviceversion.yaml
Labels: READY FOR REVIEW
